- name: JAVA
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Java | Accept License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Java | Install java 8
  apt: pkg={{ item }} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
