- name: JAVA
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes


- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install java 8
  apt: pkg={{ item }} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
