- name: Create moodle data root directory
  file:
    path: '/mnt/efs/{{ moodle_dataroot }}'
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Create moodle general cache folder
  file:
    path: /var/cache/moodlecache
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Getting Moodle
  unarchive:
    src: '{{ moodle_download_url }}'
    dest: /var/www/
    remote_src: True

- name: Move htdocs to moodlehtml
  command: mv /var/www/htdocs /var/www/moodlehtml

- name: Remove zip file
  file: path=/tmp/htdocs.zip state=absent

# - name: checkout moodle src
  # git:
    # repo: 'https://github.com/moodle/moodle.git'
    # depth: 1
    # version: MOODLE_29_STABLE
    # dest: /var/www/moodlehtml

- name: checkout moodle benchmark plugin
  git:
    repo: 'https://github.com/mikasmart/benchmark.git'
    depth: 1
    dest: /var/www/moodlehtml/report/benchmark

- name: checkout jmeter plan maker
  git:
    repo: 'https://github.com/dcai/moodle-report_loadtesting.git'
    depth: 1
    dest: /var/www/moodlehtml/report/loadtesting

- name: moodle config.php
  template:
    src: templates/moodleconfig.php
    dest: /var/www/moodlehtml/config.php

- name: moodle index.php
  template:
    src: templates/moodleindex.php
    dest: /var/www/moodlehtml/index.php

- name: Change moodle directory ownership
  file:
    dest: /var/www/moodlehtml
    recurse: yes
    state: directory
    owner: www-data
    group: www-data

# - name: Copy database dump file
  # copy:
    # src: dump.sql.bz2
    # dest: /tmp
# - name: Restore database
  # mysql_db:
    # name: my_db
    # state: import
    # target: /tmp/dump.sql.bz2
