---
- name: MySQL | Install MySQL Server
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start MySQL service
  service:
    name: "mysql"
    state: started
    enabled: yes

- name: MySQL | Setup MySQL root password
  mysql_user:
    name: "root"
    password: "mysql"
    host: "{{ item }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Setup MySQL creds for root user
  template:
    src: templates/mysql
    dest: "/root/.my.cnf"
    owner: "root"
    mode: 0600

- name: MySQL | Delete blank MySQL users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Drop MySQL test database
  mysql_db:
    name: test
    state: absent

- name: MySQL | Setup empty database for moodle
  mysql_db:
    name: "moodle"
    encoding: "utf8"
    collation: "utf8_unicode_ci"
    state: "present"
    login_user: "root"
    login_password: "mysql"

- name: MySQL | Setup MySQL user for Moodle
  mysql_user:
    name: "moodle"
    password: "moodle"
    host: "localhost"
    priv: "moodle.*:ALL"
    state: "present"
