- name: Install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - memcached
    - git
    - tig
    - unzip
    - xz-utils
    - unrar
    - htop
    - aptitude
    - vim
    - mysql-client
    - mcrypt
    - ruby
    - tig
    - tmux
    - tree
    - python-pip
    - software-properties-common

