- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: Install PHP and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - php5.6
    - php5.6-fpm
    - php5.6-cli
    - php5.6-intl
    - php5.6-curl
    - php5.6-gd
    - php5.6-imagick
    - php5.6-mysql
    - php5.6-xml
    - php5.6-xmlrpc
    - php5.6-soap
    - php5.6-mbstring
    - php5.6-zip
    - php5.6-xdebug
    - php-memcached
    - php-redis

- stat: path=/usr/local/bin/composer
  register: composer_folder

- name: PHP | Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: composer_folder.stat.isdir is not defined
